# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-de10"
BBFILE_PATTERN_meta-de10 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-de10 = "6"

LAYERDEPENDS_meta-de10 = "core"
LAYERSERIES_COMPAT_meta-de10 = "scarthgap"
